name = "SafeVerify"
version = "0.1.0"
keywords = []

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "SafeVerify"

[[lean_exe]]
name = "safe_verify"
root = "Main"
supportInterpreter = true